/** Sprünge des Slices. DD in der Größenordnung der 10-m-Tabelle. unlockAt = Karrierepunkte. */
export const DIVES = [
  {
    id: '101C',
    name: 'Kopfsprung vorwärts gehockt',
    summary: 'Ein halber Salto. Zum Lernen von Absprung, Öffnen und Rip.',
    dd: 1.4,
    level: 'Anfänger',
    somersaults: 0.5,
    twistHalves: 0,
    position: 'C',
    powerBand: [0.56, 0.82],
    unlockAt: 0,
  },
  {
    id: '103B',
    name: '1½ Salto vorwärts gehechtet',
    summary: 'Mehr Rotation: die Hocke muss sitzen, das Öffnen auch.',
    dd: 1.6,
    level: 'Fortgeschritten',
    somersaults: 1.5,
    twistHalves: 0,
    position: 'B',
    powerBand: [0.7, 0.92],
    unlockAt: 0,
  },
  {
    id: '5132D',
    name: '1½ Salto vorwärts mit 1 Schraube',
    summary: 'Wie der Salto, plus zwei Schrauben-Taps im Takt.',
    dd: 2.0,
    level: 'Experte',
    somersaults: 1.5,
    twistHalves: 2,
    position: 'D',
    powerBand: [0.74, 0.96],
    unlockAt: 32,
  },
  {
    id: '401C',
    name: 'Delphin-Kopfsprung gehockt',
    summary: 'Kurzer Kopfsprung mit engerem Kraftfenster.',
    dd: 1.5,
    level: 'Anfänger',
    somersaults: 0.5,
    twistHalves: 0,
    position: 'C',
    powerBand: [0.64, 0.78],
    unlockAt: 18,
  },
  {
    id: '105C',
    name: '2½ Salto vorwärts gehockt',
    summary: 'Viel Drehung. Das Öffnen muss früh genug sitzen.',
    dd: 2.2,
    level: 'Fortgeschritten',
    somersaults: 2.5,
    twistHalves: 0,
    position: 'C',
    powerBand: [0.76, 0.93],
    unlockAt: 48,
  },
  {
    id: '107C',
    name: '3½ Salto vorwärts gehockt',
    summary: 'Hoher DD. Nur mit festem Absprung und sauberem Öffnen.',
    dd: 2.8,
    level: 'Experte',
    somersaults: 3.5,
    twistHalves: 0,
    position: 'C',
    powerBand: [0.82, 0.96],
    unlockAt: 76,
  },
];

export function getDiveById(id) {
  return DIVES.find((dive) => dive.id === id) ?? null;
}
